### ISSUE TITLE
Document all the Step functions

### ISSUE THREAD

**Issue by Smat26** [Cloudkibo/KiboPush_Automated_Testing#14] opened 2018-01-17 19:03 UTC
For documentation purpose, there should be a list of functions that we have implemented on steps, in our Test Plan steps, this would provide an easy reference as to what our Automated Testing can achieve.

**Comment by bjafri5** [comment] 2018-01-18 10:14
Currently documented functions are here:
https://docs.google.com/spreadsheets/d/1lJ-dZOSxjuLS7MJJBFrWcZkkjVvpIGWV3MwWss0UT5E/edit#gid=1683919152

**Comment by bjafri5** [comment] 2018-01-28 04:50
This is now a duplicate of 
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/17
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/18 
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/19
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/20
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/21
https://github.com/Cloudkibo/KiboPush_Automated_Testing/issues/22
So I'm closing this.

**Closed by bjafri5** 2018-01-28 04:50 UTC
